define(['app'], function(app){
    return app.config(['$routeProvider', function ($routeProvider) {
        $routeProvider
              .when('/loading',{
					templateUrl:'./view/doctor/smokingAssessment/ca_1loading.html',
					controller:"testController"
				})
				.when('/SAssessmentReport',{
					templateUrl:'./view/doctor/CcAssessmentReport/Cc_smokingAssessmentReport.html',
					controller:"SAReportController"
				})
				.when('/accountInformation',{
					templateUrl:'./view/doctor/accountInformation/e02-1_accountInformation.html',
					controller:"AInformationController"
				})
				.when('/updateCase',{
					templateUrl:'./view/doctor/C02_2updateCase.html',
					controller:"updateCaseController"
				})
				.when('/healthRecords',{
					templateUrl:'./view/doctor/healthRecords/c02_3healthrecords.html',
					controller:"healthRecordsController"
				})
				.when('/healthRecordsDetails',{
					templateUrl:'./view/doctor/healthRecords/healthData/c03_2healteDetails.html',
					controller:"healteDetailsController"
				})
				.when('/addHealthRecords',{
					templateUrl:'./view/doctor/healthRecords/c03_3addHealthRecords.html',
					controller:"addHealthRecordsController"
				})
				.when('/myAssessment',{
					templateUrl:'./view/doctor/myAssessment/c02_4myAssessment.html',
					controller:"myAssessmentController"
				})
				.when('/smokingAssessment',{
					templateUrl:'./view/doctor/myAssessment/c03_4smokingAssessment.html',
					controller:"smokingAssessmentController"
				})
				.when('/imageAssessmen',{
					templateUrl:'./view/doctor/myAssessment/c03_5imageAssessment.html',
					controller:"imageAssessmenController"
				})
				.when('/medicalRecords',{
					templateUrl:'./view/doctor/medicalRecords/e02_4medicalRecords.html',
					controller:"medicalRecordsController"
				})
				.when('/mobileNumber',{
					templateUrl:'./view/A_binding/A01_1mobileNumber.html',
					controller:"mobileNumberController"
				})
				.when('/nickName',{
					templateUrl:'./view/doctor/accountInformation/c03_1nickName.html',
					controller:"nickNameController"
				})
				.when('/heightWeight',{
					templateUrl:'./view/doctor/healthRecords/healthData/heightWeight/c04_1heightWeightAdd.html',
					controller:"heightWeightController"
				})
				.when('/adddata',{
					templateUrl:'./view/doctor/healthRecords/healthData/heightWeight/c05_1adddata.html',
					controller:"adddataController"
				})
				.when('/smoking',{
					templateUrl:'./view/doctor/healthRecords/healthData/c04_2smoking.html',
					controller:"smokingController"
				})
				.when('/cases',{
					templateUrl:'./view/doctor/healthRecords/healthData/c04_5cases.html',
					controller:"casesController"
				})
				.when('/images',{
					templateUrl:'./view/doctor/healthRecords/healthData/c04_6images.html',
					controller:"imagesController"
				})
				.when('/imagesAssessment',{
					templateUrl:'./view/doctor/CcAssessmentReport/Cc_2imagesAssessmentReport.html',
					controller:"IAReportController"
				})
				.when('/imagesLoading',{
					templateUrl:'./view/doctor/cb_imagesAssessment/cb_1loading.html',
					controller:"imagesLoadingController"
				})
				.when('/index', {
					templateUrl: "./view/doctor/E01_1doctor.html",
					controller: "doctorController"
				})
				.when('/seeThedetails', {
					templateUrl: "./view/doctor/medicalRecords/c03_6seeThedetails.html",
					controller: "seeThedetailsController"
				})
				.when('/relationship',{
					templateUrl:'./view/dcotor/healthRecords/c03-a1relationship.html',
					controller:"relationshipController"
				})
				.when('/myCollection',{
					templateUrl:'./view/doctor/myCollection/e02-3_myCollection.html',
					controller:"myCollectionController"
				})
				.when('/todayMedical',{
					templateUrl:'./view/doctor/medicalRecords/e02_5todayMedical.html',
					controller:"todayMedicalController"
				})
				.when('/patientManagement',{
					templateUrl:'./view/doctor/patientManagement/e02_2patientManagement.html',
					controller:"patientManagementController"
				})
				.when('/choosePatient',{
					templateUrl:'./view/doctor/patientDetails/e03_2choosePatient.html',
					controller:"choosePatientController"
				})	
				.when('/patientInformation',{
					templateUrl:'./view/doctor/patientDetails/e03_3patientInformation.html',
					controller:"patientInformationController"
				})	
				.when('/healthyInformation',{
					templateUrl:'./view/doctor/patientDetails/e04_3healthyInformation.html',
					controller:"healthyInformationController"
				})
				.when('/medicalDetails',{
					templateUrl:'./view/doctor/healthRecords/healthData/e04_4medicalDetails.html',
					controller:"medicalDetailsController"
				})
				.when('/myCode',{
					templateUrl:'./view/doctor/medicalRecords/e02_6myCode.html',
					controller:"myCodeController"
				})
				.when('/newPatient',{
					templateUrl:'./view/doctor/patientDetails/e03_4newPatient.html',
					controller:"newPatientController"
				})
				.when('/relatedImage',{
					templateUrl:'./view/doctor/healthRecords/healthData/e05_2relatedImage.html',
					controller:"relatedImageController"
				})
				.when('/relatedRecord',{
					templateUrl:'./view/doctor/healthRecords/healthData/e05_2relatedRecord.html',
					controller:"relatedRecordController"
				})
				.when('/diagnoseDetails',{
					templateUrl:'./view/doctor/patientDetails/e04_6diagnoseDetails.html',
					controller:"diagnoseDetailsController"
				})
				.when('/predictTable',{
					templateUrl:'./view/doctor/patientDetails/e03_5predictTable.html',
					controller:"predictTableController"
				})
				.when('/basicInformation',{
					templateUrl:'./view/D_qualification/D_theBasicInformation.html',
					controller:"basicInformationController"
				})	
				.when('/professionalInformation/:hospitalid/:hospitalname',{
					templateUrl:'./view/D_qualification/D002_professionalInformation.html',
					controller:"professionalInformationController"
				})	
				.when('/professionalInformation2',{
					templateUrl:'./view/D_qualification/D003_professionalInformation2.html',
					controller:"professionalInformation2Controller"
				})	
				.when('/professionalInformation3',{
					templateUrl:'./view/D_qualification/D004_professionalInformation3.html',
					controller:"professionalInformation3Controller"
				})
				.when('/chooseHospital',{
					templateUrl:'./view/D_qualification/d01_1chooseHospital.html',
					controller:"chooseHospitalController"
				})
				.when('/matchHospital',{
					templateUrl:'./view/D_qualification/d01-2matchHospital.html',
					controller:"matchHospitalController"
				})
				.when('/mobileNumber',{
					templateUrl:'./view/D_qualification/A01_1mobileNumber.html',
					controller:"mobileNumberController"
				})
				.otherwise({
					redirectTo: '/index'
				})
    }]);
});
